language: minimal
services:
  - docker

jobs:
  include:
    - os: linux
      stage: Build image
      arch: amd64
      script:
        - docker build -t vlakam/eventy-bot:amd64 .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push vlakam/eventy-bot:amd64
    - os: linux
      arch: arm64
      script:
        - docker build -t vlakam/eventy-bot:arm64 .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push vlakam/eventy-bot:arm64
    - os: linux
      arch: amd64
      stage: Push manifesto
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
        - chmod +x manifest-tool
        - ./manifest-tool push from-spec docker-multi-arch-manifest.yaml